=== ramcharansaiteja/WEB-/03-03-26/2nd question/books.dtd
<!ELEMENT Books (Book+)>

<!ELEMENT Book (Title, AuthorName, ISBN, PublisherName, Edition, Price)>

<!ELEMENT Title (#PCDATA)>
<!ELEMENT AuthorName (#PCDATA)>
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT PublisherName (#PCDATA)>
<!ELEMENT Edition (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== ramcharansaiteja/WEB-/03-03-26/2nd question/books.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Books SYSTEM "books.dtd">

<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="books.xsd">

    <Book>
        <Title>XML Fundamentals</Title>
        <AuthorName>John Smith</AuthorName>
        <ISBN>9781234567890</ISBN>
        <PublisherName>TechPress</PublisherName>
        <Edition>3</Edition>
        <Price>450.50</Price>
    </Book>

    <Book>
        <Title>Web Technologies</Title>
        <AuthorName>Mary Johnson</AuthorName>
        <ISBN>9780987654321</ISBN>
        <PublisherName>WebWorld Publications</PublisherName>
        <Edition>2</Edition>
        <Price>399.00</Price>
    </Book>

</Books>
